app_name: mongoflow
app_title: MongoFlow
default_title: "MongoFlow : Community Filtered MongoDB News"
sub_title: "Community-maintained MongoDB News"
app_url: http://mongoflow.heroku.com/
rss_url: http://feeds.feedburner.com/Mongoflow
meta_keywords: "mongo, Mongodb news, mongodb blog, mongodb, json"
meta_author: "Brian Scott"
body_class: mongoflow

# Set this to true for a more fancy interface, but for the cost of page load time
uses_javascript: false

# Edit expiration default: 60 (this means that editing ends 60 minutes after last update of item)
# Set to 0 or omit to always allow editing of items by its owner
edit_expiration_in_minutes: 60